### ISSUE TITLE
--url Parameter Supported?

### ISSUE THREAD

**Issue by dmeltzer** [OpenNMS/onmsctl#3]
Hello,

I might be doing something wrong, but I'm trying to use onmsctl on a remote system, and when I pass the URL parameter it still wants to connect to localhost.  Is there a trick that I'm missing?

```
☁  onmsctl [master] ⚡ ./onmsctl --url "http://snoopy.***:8980" info
ERROR: Get http://localhost:8980/opennms/rest/info: dial tcp [::1]:8980: connect: connection refused
```

**Comment by agalue** [comment]
Hi!

Thanks for trying out the tool. I really appreciate it.

I'll check to see why the url flag is not working as intended.

**Comment by dmeltzer** [comment]
I just saw the note in the readme about the .yaml file and configuring the URL does behave there, so I've solved it for my current needs at least.

**Comment by agalue** [comment]
Excellent! You're right, having a `config.yaml` works, but the problem you've reported is legit. I'll  apply a fix in a few minutes.

**Comment by agalue** [comment]
Fixed!
